- plugins/module_utils/sops.py
Errors were not being displayed due to missing `to_text` on error output.
Add `to_text` in module_utils/sops.py.
Conversation in [this pr](https://github.com/ansible-collections/community.sops/pull/6).
[Previous pull request from wrong branch](https://github.com/ansible-collections/community.sops/pull/10).
> Fix error output

- plugins/lookup/sops.py
As noted in #16 the inline documentation in `sops` lookup plugin is wrong.
- fix docs referencing proper FQCN
Thanks @ThomasSteinbach for noticing!
> Fix lookup sops not found

- README.md
- plugins/action/load_vars.py
- plugins/modules/load_vars.py
- plugins/vars/sops.py
- tests/integration/targets/load_vars/aliases
- tests/integration/targets/load_vars/meta/main.yml
- tests/integration/targets/load_vars/tasks/main.yml
- tests/integration/targets/load_vars/vars/.sops.yaml
- tests/integration/targets/load_vars/vars/empty.sops.json
- tests/integration/targets/load_vars/vars/proper-vars-2.sops.yaml
- tests/integration/targets/load_vars/vars/proper-vars.sops.yaml
- tests/integration/targets/load_vars/vars/simple.sops.yaml
- tests/integration/targets/load_vars/vars/wrong.yaml
It would be nice to be able to use `vars_files` and `include_vars` with sops-encrypted YAML/JSON files. Unfortunately, that does not work, since there are no vault plugins yets (both directives/actions work with raw files and Ansible Vault, but not with anything else).
This adds a simple `load_vars` plugin, which behaves similarly to `include_vars`, but decodes sops-encrypted YAML/JSON files.
It only imports the file parts of `include_vars`, not the directory parts.
Also, by default, it does NOT treat the loaded values as variables, but as facts. This can be changed by setting `static: false`, but this functionality relies on a hack. I used another name (I originally wanted to use `include_sops_vars`) so the "proper" name can be used once this can be properly implemented without a hack.
> Add load_vars action plugin

- plugins/lookup/sops.py
- plugins/module_utils/sops.py
- tests/integration/targets/lookup_sops/files/binary.sops
- tests/integration/targets/lookup_sops/files/rstrip.sops
- tests/integration/targets/lookup_sops/tasks/main.yml
Adds two options to the lookup plugin:
- `rstrip` (type `bool`, default value `true`): whether to rstrip the result or not;
- `base64` (type `bool`, default value `false`): whether to base64-encode the result and treat the sops output as binary data.
Right now I'm needing that for the tests for #23, but I think these are two additions which can be pretty useful.
> Extend lookup plugin

- README.md
As `sops` is required to be installed by hand, knowing the version is supposed to be compatible with helps with installing the correct version.
Add `mozilla/sops` and `community.sops` compatibility matrix.
> Include sops compatibility matrix in README

- README.md
- plugins/module_utils/io.py
- plugins/module_utils/sops.py
- plugins/modules/sops_encrypt.py
- tests/integration/targets/sops_encrypt/aliases
- tests/integration/targets/sops_encrypt/files/.sops.yaml
- tests/integration/targets/sops_encrypt/files/broken-json-yaml
- tests/integration/targets/sops_encrypt/files/wrong.yaml
- tests/integration/targets/sops_encrypt/meta/main.yml
- tests/integration/targets/sops_encrypt/tasks/main.yml
This module allows to encrypt data (with idempotency). It accepts text data, binary data, JSON data or YAML data.
That allows to create roles or playbooks which encrypt data without having to fiddle with with sops calls yourself (which is non-trivial if you strive for idempotency, or don't want to write plaintext data to disk).
> Add sops_encrypt module

- README.md
- plugins/action/load_vars.py
- plugins/modules/load_vars.py
- tests/integration/targets/load_vars/tasks/main.yml
- tests/integration/targets/load_vars/vars/proper-vars-2.sops.yaml
- tests/integration/targets/load_vars/vars/proper-vars.sops.yaml
Fixes #25 by removing the `static` option of `load_vars`. Instead, it adds a `expressions` option with values `ignore` and `evaluate-now`. If Ansible will ever allow action plugins to define proper variables, we can add a new option value `evaluate-on-use`, which would be a proper replacement for `static: false`. The value `evaluate-now` is a better-than-nothing replacement, which in some use-cases (like mine) is good enough.
> load_vars: change 'static' option to 'expressions' option

- README.md
- plugins/vars/sops.py
- tests/integration/targets/var_sops/runme.sh
- tests/integration/targets/var_sops/test-bad-file/hosts
- tests/integration/targets/var_sops/test-not-dir/hosts
- tests/integration/targets/var_sops/test-stage-inv-cache/.gitignore
- tests/integration/targets/var_sops/test-stage-inv-cache/hosts
- tests/integration/targets/var_sops/test-stage-inv-cache/playbook.yml
- tests/integration/targets/var_sops/test-stage-inv-cache/run.sh
- tests/integration/targets/var_sops/test-stage-inv-no-cache/.gitignore
- tests/integration/targets/var_sops/test-stage-inv-no-cache/hosts
- tests/integration/targets/var_sops/test-stage-inv-no-cache/playbook.yml
- tests/integration/targets/var_sops/test-stage-inv-no-cache/run.sh
- tests/integration/targets/var_sops/test-stage-task-cache/.gitignore
- tests/integration/targets/var_sops/test-stage-task-cache/hosts
- tests/integration/targets/var_sops/test-stage-task-cache/run.sh
- tests/integration/targets/var_sops/test-stage-task-no-cache/.gitignore
- tests/integration/targets/var_sops/test-stage-task-no-cache/hosts
- tests/integration/targets/var_sops/test-stage-task-no-cache/run.sh
- tests/integration/targets/var_sops/test-success/hosts
There is a bug in ansible: if `localhost` is only implicitly defined (i.e. you don't define it yourself in the inventory), then vars plugins don't work properly for it. Therefore I added inventories with explicit `localhost` entries for the vars plugin. This also changes the test outcomes. I also updated the docs.
> Improve inventory tests, and improve staging docs

- README.md
- meta/runtime.yml
To conform to the collection checklist, we need to declare a minimal supported Ansible version (https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst#metaruntimeyml). I've picked 2.9.10, since this is the minimal version of 2.9 which got some deprecation-related things backported. Trying to do deprecations by code which are accepted by the sanity tests of Ansible 2.10 and 2.11 is only possible with 2.9.10 or later without crashing. We don't deprecate anything yet, but it's better to avoid having to bump the minimal Ansible version supported in case we ever need to deprecate something.
Also, Ansible 2.9 and 2.8 do not know about meta/runtime.yml, so one can still use the parts of the collection that work with it with older versions without any problems. It's …
> Declare minimal Ansible version

- changelogs/fragments/33-lookup-empty_on_not_exist.yml
- plugins/lookup/sops.py
- tests/integration/targets/lookup_sops/tasks/main.yml
This makes implementing things a lot easier. Instead of first having to do a stat to see if it really exists, one can simply specify `empty_on_not_exist=true` to the lookup and obtain an empty string instead of an error.
I'm using this in https://github.com/felixfontein/ansible-acme/ (I'm right now working on adding sops-encrypted keys support).
> Allow to tell sops lookup to return '' for non-existant files

- plugins/lookup/sops.py
- plugins/vars/sops.py
According to https://github.com/ansible/ansible/issues/71795, `<plugin_type>:` should be replaced by `name:` in the plugin docs.
I marked this as [WIP] since it should wait until ansible/ansible#71734 is finalized.
collection
> Fix plugin sanity tests

- CHANGELOG.rst
- changelogs/.plugin-cache.yaml
- changelogs/changelog.yaml
- changelogs/fragments/1.0.2.yml
- galaxy.yml
There is no 1.0.0 release on Galaxy, but we announced one and have one in the changelog, and there is a 1.0.1 release on Galaxy which has no changelog. To fix this, this modifies the changelog to add 1.0.1, and releases this fix as 1.0.2 so the version on Galaxy has a correct changelog.
> Fix 1.0.1 release; release 1.0.2 for that

- .github/workflows/ansible-test.yml
Runs CI nightly (Ansible 3.0.0 requirements are that CI runs at least once per week).
Also updates the GHA workflow to be more similar to the one in https://github.com/ansible-collections/collection_template/.
> Run CI nightly; update GHA workflow

- changelogs/fragments/51-fix-vars-arguments.yml
- plugins/doc_fragments/sops.py
- plugins/lookup/sops.py
- plugins/vars/sops.py
- tests/integration/targets/lookup_sops/tasks/main.yml
I used the wrong syntax in #47.
> vars and lookup plugins: fix syntax in Ansible vars specification so options can actually provided with vars

- changelogs/fragments/54-no_log-fixes.yml
- plugins/module_utils/sops.py
More fallout from ansible/ansible#73508.
We should release this as 1.0.4 ASAP.
> sops_encrypt: mark parameters containing secrets with no_log=True

- .github/workflows/ansible-test.yml
As per https://github.com/ansible-collections/overview/issues/45#issuecomment-776930466 from 1st of March `ubuntu1604` will not be supported anymore as available testing container.
- Remove `ubuntu1604` from containers in the integration test matrix
To be merged before 1st March 2021
> Remove `ubuntu16.04` from containers used for testing

- changelogs/fragments/56-sops_encrypt-yaml-output.yaml
- plugins/modules/sops_encrypt.py
Signed-off-by: Christian Hernvall <c.hernvall@yubico.com>
Use output_type `yaml` for sops_encrypt towards YAML files (`*.yaml`).
See motivation.
First contribution to an Ansible community project. Let me know if I've missed something!
> sops_encrypt: YAML output type towards .yaml paths

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/config.yaml
Since all content cannot be used without FQCNs (or the dreaded `collections:` keyword in case of actions/modules), I think we should use them in the changelog as well. This PR modifies the changelog config so that auto-generated entries (new modules/plugins/...) automatically use FQCN.
@endorama what do you think? Should we also update other existing entries to use FQCN, like `community.sops.sops vars plugins - remove non-working Ansible variables` instead of `sops vars plugins - remove non-working Ansible variables` (https://github.com/ansible-collections/community.sops/blob/main/CHANGELOG.rst#bugfixes)?
> Use FQCNs for new module/plugin announcements in changelog

- changelogs/fragments/58-actionmodule-plugin-utils-ansible-core-2.11.yml
- plugins/plugin_utils/action_module.py
Since we copied some code from community.crypto which was broken by a change in ansible-core 2.11.0b3, we also have to fix it there. This copies the fix from ansible-collections/community.crypto#202 to community.sops.
(For reference: ansible/ansible#73983)
> Make action_module plugin utils compatible with latest changes in ansible-core 2.11.0b3

- README.md
The module is named sops_encrypt, not encrypt_sops.
> README: correct module name

- docs/docsite/extra-docs.yml
- docs/docsite/rst/guide.rst
This adds a scenario guide which will be shown on the Ansible docsite (once this appears in a new Ansible release). A preview is available here: https://ansible.fontein.de/collections/community/sops/ (the guide itself is https://ansible.fontein.de/collections/community/sops/docsite/guide.html)
> Add basic scenario guide

- changelogs/fragments/ansible-core-_text.yml
- plugins/action/load_vars.py
- plugins/filter/decrypt.py
- plugins/lookup/sops.py
- plugins/module_utils/sops.py
- plugins/modules/sops_encrypt.py
- plugins/plugin_utils/action_module.py
- plugins/vars/sops.py
While the private API `ansible.module_utils._text` was the default place to get `to_text`, `to_bytes` and `to_native` for a long time, at least since Ansible 2.9 there's a non-private alternative: `ansible.module_utils.common.text.converters`. So let's use it :)
- Feature Pull Request
various plugins
> Replace ansible.module_utils._text by ansible.module_utils.common.text.converters

- .github/workflows/ansible-test.yml
- tests/integration/targets/setup_remote_tmp_dir/handlers/main.yml
- tests/integration/targets/setup_remote_tmp_dir/tasks/default-cleanup.yml
- tests/integration/targets/setup_remote_tmp_dir/tasks/default.yml
- tests/integration/targets/setup_remote_tmp_dir/tasks/main.yml
- tests/integration/targets/setup_sops/tasks/install.yml
- tests/integration/targets/setup_sops/tasks/main.yml
- tests/integration/targets/sops_encrypt/meta/main.yml
- tests/integration/targets/sops_encrypt/tasks/main.yml
Contains all fixes from #76 that are not specific to split-controller testing being available. These fixes weren't needed so far since for ansible-test, controller == remote. This will change with split-controller testing, and thus these fixes are necessary.
> Improve CI

- changelogs/fragments/81-plugin-options.yml
- plugins/doc_fragments/sops.py
- plugins/lookup/sops.py
- plugins/vars/sops.py
Fixes #80.
Allows to configure generic plugin options with ansible.cfg keys and env variables.
> Allow to configure plugins with ansible.cfg keys and env variables

- plugins/filter/decrypt.py
- tests/sanity/extra/no-unwanted-files.py
Add filter documentation using the new sidecar docs feature for ansible-core 2.13. Rendered with https://github.com/ansible-community/antsibull-docs/pull/6 to: https://ansible.fontein.de/collections/community/sops/index.html#filter-plugins
filter plugin documentation
> Add filter documentation

- changelogs/fragments/114-disable-vars-plugin.yml
- plugins/vars/sops.py
- tests/integration/targets/var_sops/test-disable-sops/group_vars
- tests/integration/targets/var_sops/test-disable-sops/hosts
- tests/integration/targets/var_sops/test-disable-sops/playbook.yml
- tests/integration/targets/var_sops/test-disable-sops/run.sh
- tests/integration/targets/var_sops/test-disable-sops/validate.sh
AWX stores all variables that it can parse which is very bad for security sensitive stuff :)
I added a new env variable `SOPS_ANSIBLE_AWX_DISABLE_VARS_PLUGIN_TEMPORARILY` to disable the plugin temporarily. Can be used in AWX via a custom credential on the inventory source.
> Added configuration to temporarily disable the vars plugin (eg in AWX).

- changelogs/fragments/117-age.yml
- plugins/doc_fragments/sops.py
- plugins/filter/decrypt.py
- plugins/module_utils/sops.py
- tests/integration/targets/age/aliases
- tests/integration/targets/age/meta/main.yml
- tests/integration/targets/age/tasks/main.yml
- tests/integration/targets/age/tasks/test.yml
> Add age support

- changelogs/fragments/121-action-module-compat.yml
- plugins/plugin_utils/action_module.py
See https://github.com/ansible/ansible/pull/78860.
plugins/plugin_utils/action_module.py
> Action plugin support code: ensure compatibility with newer versions of ansible-core

- tests/integration/targets/setup_sops/tasks/install.yml
- tests/integration/targets/setup_sops/tasks/main.yml
This should make CI more reliable. Right now it often fails with GitHub API rate limitings (see for example https://github.com/ansible-collections/community.sops/actions/runs/3728549456/jobs/6324270637) since the install role (with latest) is run multiple times per CI run.
> CI: avoid running install roles more than twice (localhost and remote) for tests

- .github/workflows/ansible-test.yml
Currently CI fails because of this.
> CI: Use Fedora 37 container instead of Fedora 36 container, which has been removed from devel

- plugins/modules/sops_encrypt.py
- tests/sanity/extra/extra-docs.json
- tests/sanity/extra/extra-docs.py
Use `antsibull-docs lint-collection-docs --plugin-docs` to do additional documentation validation. This is important if the docs build workflow is no longer there (#6344).
This also ensures that no semantic markup is used. This should be changed once the last Ansible 6.x.y release is out containing this collection; from then on we can (relatively) safely start using semantic markup without defacing the Ansible 7 (or before) documentation.
CI
> Do extra docs validation; explicitly disallow semantic markup in docs

- .github/workflows/ansible-test.yml
Ref: https://github.com/ansible-community/images/pull/56
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/43
CI
> CI: Arch Linux now uses Python 3.11

- .github/workflows/ansible-test.yml
Currently CI fails because it tries to use Python 3.8 wiht CentOS 8 Stream.
> CI: CentOS 8 Stream now only provides Python 3.6 and 3.9

- tests/ee/all.yml
- tests/ee/roles/lookup_sops/tasks/main.yml
- tests/integration/targets/age/tasks/test.yml
- tests/integration/targets/filter_decrypt/tasks/main.yml
- tests/integration/targets/load_vars/tasks/main.yml
- tests/integration/targets/lookup_sops/tasks/main.yml
- tests/integration/targets/setup_sops/tasks/install.yml
- tests/integration/targets/setup_sops/tasks/main.yml
- tests/integration/targets/sops_encrypt/tasks/main.yml
~~This should avoid tests that we *expect* to (likely) fail to be reported as "failed" in the GHA summary (see for example https://github.com/ansible-collections/community.sops/actions/runs/5031515902).~~ Seems that only shows up inbetween, not in the final summary :shrug:
Anyway, I think this is cleaner, so let's see how this goes.
> Integration tests: use failed_when instead of ignore_errors

- .github/workflows/ee.yml
- changelogs/fragments/146-install-facts.yml
- roles/install/tasks/main.yml
> install role: make sure pkg_mgr fact is available for localhost installs

- README.md
- changelogs/fragments/151-github.yml
- docs/docsite/rst/guide.rst
- galaxy.yml
- plugins/filter/decrypt.py
- plugins/module_utils/sops.py
- roles/install/meta/argument_specs.yml
- roles/install/meta/main.yml
- roles/install/tasks/github_api.yml
- roles/install/tasks/github_latest_release.yml
- roles/install/vars/OS-Debian.yml
- roles/install/vars/OS-RedHat.yml
- tests/ee/all.yml
- tests/integration/targets/setup_sops/tasks/install.yml
- tests/integration/targets/var_sops/README.md
This breaks the installation role in some cases. This PR fixes the installation role and updates all references to the new GH organization.
> sops moved from gh.com/mozilla/sops to gh.com/getsops/sops

- .github/workflows/ansible-test.yml
- .github/workflows/ee.yml
ansible-core devel now needs Python 3.10+, but the RHEL UBI 9 does not have Python 3.10 support yet apparently.
EE CI
> Disable EE with ansible-core devel for now until UBI 9 has Python 3.10 support

- README.md
IMHO it would be good for new users of the SOPS module to quickly be able to find out that the age encryption tool is supported.
With this commit there’s a mention of age in the README file.
> Mention the age encryption tool in the readme

- .github/workflows/ansible-test.yml
- README.md
- changelogs/fragments/159-new-releases.yml
- plugins/filter/_latest_version.py
- roles/install/meta/argument_specs.yml
- roles/install/vars/OS-Debian.yml
- roles/install/vars/OS-RedHat.yml
- tests/integration/targets/filter__latest_version/aliases
- tests/integration/targets/filter__latest_version/tasks/main.yml
https://github.com/getsops/sops/releases/tag/v3.8.0-rc.1
> Test with 3.8.0-rc1, fix install role to handle 3.8.0-rc1 correctly and avoid prereleases if asked for the latest version

- changelogs/fragments/165-yaml-output-for-yml-extension.yaml
- plugins/modules/sops_encrypt.py
Closes #164
- Changed `sops_encrypt` module to also use `yaml` output on `.yml` files
> Use yaml output on .yml files too

- tests/integration/targets/role_install_latest/meta/main.yml
- tests/integration/targets/role_install_localhost_remote/meta/main.yml
- tests/integration/targets/role_install_version/meta/main.yml
- tests/integration/targets/setup_pkg_mgr/tasks/archlinux.yml
- tests/integration/targets/setup_pkg_mgr/tasks/main.yml
- tests/integration/targets/setup_sops/meta/main.yml
Hopefully fixes nightly CI failures (https://github.com/ansible-collections/community.sops/actions/runs/6609135034). These most likely stem from Arch upgrading sops to 3.8.1, while the Arch Docker image is from 23 hours ago when sops still was at 3.8.0.
> CI: make sure that Arch images are updated first

- .github/workflows/ansible-test.yml
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/63
CI
> CI: devel supports Fedora 39, and no longer Fedora 38

- plugins/doc_fragments/sops.py
requirement was missing
adds requirement to sops binary
> add requirement to sops binary

- .github/workflows/ansible-test.yml
Need to adjust the CI matrix.
Ref: https://github.com/ansible-community/images/pull/74
Ref: https://forum.ansible.com/t/5187
CI
> CI: Arch Linux switched to Python 3.12

- .github/workflows/ansible-test.yml
- .github/workflows/ee.yml
According to https://www.centos.org/download/ "CentOS Stream 8 end of builds is May 31, 2024", so the build seems dead as we can no longer install things. So let's remove it.
EE tests
integration tests
> Stop building EE and testing with CentOS Stream 8, which no longer has builds

- changelogs/fragments/185-vars-valid-extensions.yml
- plugins/vars/sops.py
- tests/integration/targets/vars_sops/test-extensions/group_vars/all.yml
- tests/integration/targets/vars_sops/test-extensions/group_vars/all/test.yml
- tests/integration/targets/vars_sops/test-extensions/host_vars/localhost.json
- tests/integration/targets/vars_sops/test-extensions/host_vars/localhost.json.license
- tests/integration/targets/vars_sops/test-extensions/hosts
- tests/integration/targets/vars_sops/test-extensions/playbook.yml
- tests/integration/targets/vars_sops/test-extensions/run.sh
- tests/integration/targets/vars_sops/test-extensions/validate.sh
See #183.
Makes the valid extensions configurable by the `valid_extensions` option in the `[community.sops]` section of ansible.cfg, or by the `ANSIBLE_VARS_SOPS_PLUGIN_VALID_EXTENSIONS` environment variable.
Fixes #183.
> vars plugin: make valid_extensions configurable

- .github/workflows/ansible-test.yml
- README.md
- changelogs/fragments/188-sops-3.9.0.yml
- roles/install/vars/OS-RedHat.yml
[sops 3.9.0](https://github.com/getsops/sops/releases/tag/v3.9.0) has just been released!
Unfortunately the RPM URLs changed once again... (Ref: https://github.com/getsops/sops/issues/1547)
> Make sure 3.9.0 is tested in CI and mentioned in README; fix RPM URLs again

- CHANGELOG.md
- CHANGELOG.rst
- CONTRIBUTING.md
- README.md
- changelogs/config.yaml
- docs/docsite/rst/guide.rst
- galaxy.yml
- playbooks/install.yml
- playbooks/install_localhost.yml
- plugins/doc_fragments/sops.py
- plugins/filter/decrypt.py
- plugins/lookup/sops.py
- plugins/modules/load_vars.py
- plugins/modules/sops_encrypt.py
- plugins/vars/sops.py
- roles/_install_age/meta/main.yml
- roles/install/meta/argument_specs.yml
- roles/install/meta/main.yml
- roles/install/tasks/detect_source.yml
- roles/install/tasks/github.yml
- roles/install/tasks/main.yml
- roles/install/tasks/system.yml
- SOPS is spelled upper-case, unless the SOPS CLI tool `sops` is meant.
- Developer links to the Ansible docs should use `/devel/` instead of `/latest/` (IMO).
- Fix changelog URLs.
- Adjust YAML indent in README.
- Convert relative link in README to absolute one so that it works on Galaxy as well.
- Various other small details.
> Improve documentation

- docs/docsite/rst/guide.rst
- plugins/vars/sops.py
The names with the underscore are not used anywhere except in the code, so there's no reason to keep the underscores.
Remove the underscores.
> vars plugin: remove superfluous leading underscores from option names

- changelogs/changelog.yaml
- changelogs/fragments/200-lookup-extract.yaml
- plugins/lookup/sops.py
- plugins/module_utils/sops.py
- tests/integration/targets/lookup_sops/files/extract.json
- tests/integration/targets/lookup_sops/files/extract.json.license
- tests/integration/targets/lookup_sops/files/extract.yaml
- tests/integration/targets/lookup_sops/files/extract.yaml.license
- tests/integration/targets/lookup_sops/tasks/main.yml
We have large encrypted yaml files and would like to lookup only specific keys.
Modified the Sops.decrypt function to accept an "extract" option.
> implement `sops decrypt --extract` for lookup plugin

- changelogs/fragments/204-input-output-type-ini.yml
- plugins/filter/decrypt.py
- plugins/lookup/sops.py
This is basically #202 with the necessary documentation and changelog fragment. I cannot push directly to #202's branch, so here's a new PR for this...
Closes #202.
> sops lookup, decrypt filter: add `ini` as valid input and output type

- tests/integration/targets/vars_sops/test-disable-sops/validate.sh
Apparently the error message was changed in ansible-core devel.
> CI: make test more lenient

- .github/workflows/ansible-test.yml
Arch Linux updated to Python 3.13. See also https://github.com/ansible-community/images/pull/108.
CI
> CI: Arch Linux updated to Python 3.13

- plugins/doc_fragments/attributes.py
- plugins/modules/load_vars.py
- plugins/modules/sops_encrypt.py
- roles/install/meta/argument_specs.yml
Adds a new attribute `idempotent` for module documentation, which states whether (resp. under which circumstances) the module is idempotent.
Related PRs:
- https://github.com/ansible-collections/community.dns/pull/238
- https://github.com/ansible-collections/community.crypto/pull/833
- https://github.com/ansible-collections/community.docker/pull/1022
- https://github.com/ansible-collections/community.hrobot/pull/132
- https://github.com/ansible-collections/community.routeros/pull/337
module documentation
> Add 'idempotent' attribute

- .github/workflows/ansible-test.yml
- README.md
[SOPS 3.9.3](https://github.com/getsops/sops/releases/tag/v3.9.3) has just been released, so we should test against it as well.
> Run tests against SOPS 3.9.3

- .github/workflows/ansible-test.yml
Ref: https://github.com/ansible/ansible/pull/84281
Ref: https://github.com/ansible/ansible/pull/84525
CI
> CI: Add Fedora 41, Alpine 3.21 to CI for devel

- changelogs/fragments/224-install.yml
- roles/install/tasks/main.yml
Fixes #223.
`run_once: "{{ omit }}"` simply does not work (and probably never did)...
> install role: work around ansible-core bug

- .github/workflows/ansible-test.yml
- README.md
SOPS 3.10.0 has been released: https://github.com/getsops/sops/releases/tag/v3.10.0
> Add SOPS 3.10.0 to CI and README

- changelogs/fragments/225-data-tagging.yml
- plugins/action/load_vars.py
This adds https://github.com/ansible/ansible/pull/84621 to CI to test whether it causes problems in CI.
Ref: https://forum.ansible.com/t/data-tagging-preview-and-testing/40759
Ref: https://forum.ansible.com/t/data-tagging-playground/39909
CI
> Make ready for data tagging

- .github/workflows/ansible-test.yml
- README.md
> Cover more SOPS versions in CI

- noxfile.py
ansible-core devel updated its CI containers.
CI
> CI: Bump Alpine 3.21 to 3.22 and Fedora 41 to 42

- noxfile.py
I removed it in #250 for `devel`, but it's still available with `stable-2.19`.
> Add Alpine 3.21 back to CI

- .github/workflows/ee.yml
ansible-core devel requires Python 3.12+, and our EE test has only Python 3.11. Also the stable-1 branch generally stopped testing against ansible-core devel, and tests against ansible-core 2.19 max.
> [stable-1] CI: Replace ansible-core devel with 2.19 in EE tests

- changelogs/fragments/260-deprecations.yml
- plugins/plugin_utils/action_module.py
ansible.module_utils._text and ansible.module_utils.common._collections_compat have been deprecated.
various
> ansible-core 2.20: avoid deprecated functionality

- README.md
- antsibull-nox.toml
SOPS 3.11.0 has been released: https://github.com/getsops/sops/releases/tag/v3.11.0
> Add SOPS 3.11.0 to test matrix
