ansible-collections/community.sops

.gitignore, README.md, changelogs/config.yaml
Adjust README a bit and add [changelog generator](https://github.com/ansible-community/antsibull) config.
- Feature Pull Request
collection
=> Setup collection

.github/pull_request_template.md, CONTRIBUTING.md, README.md
Add a contributing guideline to ease onboarding new contributors.
- add `CONTRIBUTING.md`
=> Add contributing guidelines

.github/workflows/ansible-test.yml, README.md, galaxy.yml
Release to allow installing the collection using Ansible Galaxy. 
- improve `README`
- add more tags in `galaxy.yml`
Closes #5
**Note**: this PR will not be merged until the `sops` `vars` plugin has been merged.
=> Prepare release

plugins/vars/sops.py, tests/integration/targets/setup_sops/tasks/ubuntu.yml, tests/integration/targets/var_sops/aliases, tests/integration/targets/var_sops/group_vars/all.sops.yml, tests/integration/targets/var_sops/group_vars/all/test.sops.yml, tests/integration/targets/var_sops/meta/main.yml, tests/integration/targets/var_sops/runme.sh, tests/integration/targets/var_sops/setup.yml, tests/integration/targets/var_sops/test-1.yml
I don't have sops installed, so I wasn't able to generate a proper second .sops.yml file. But this is a good starting point I think :)
=> Update for #6: fix vars loading, and add simple tests

plugins/vars/sops.py, tests/integration/targets/setup_sops/tasks/ubuntu.yml, tests/integration/targets/var_sops/aliases, tests/integration/targets/var_sops/group_vars/all.sops.yml, tests/integration/targets/var_sops/group_vars/all/test.sops.yml, tests/integration/targets/var_sops/meta/main.yml, tests/integration/targets/var_sops/runme.sh, tests/integration/targets/var_sops/setup.yml, tests/integration/targets/var_sops/test-1.yml
Include in `community.sops` collection the `vars` plugin (first seen in https://github.com/ansible/ansible/pull/59641).
- add `sops` `vars` plugin
No test cases have been added for this plugin.
=> Add sops vars plugin

plugins/lookup/sops.py, plugins/vars/sops.py
Fixes some sanity (not yet) errors detected with ansible/ansible#71734.
=> Fix some sanity (not yet) errors

plugins/lookup/sops.py, plugins/module_utils/sops.py, tests/integration/targets/lookup_sops/files/hidden-binary, tests/integration/targets/lookup_sops/files/hidden-binary-yaml, tests/integration/targets/lookup_sops/files/hidden-binary-yaml.json, tests/integration/targets/lookup_sops/files/hidden-binary-yaml.yaml, tests/integration/targets/lookup_sops/files/hidden-binary.json, tests/integration/targets/lookup_sops/files/hidden-binary.yaml, tests/integration/targets/lookup_sops/files/hidden-json, tests/integration/targets/lookup_sops/files/hidden-json.json, tests/integration/targets/lookup_sops/files/hidden-json.yaml, tests/integration/targets/lookup_sops/files/hidden-yaml, tests/integration/targets/lookup_sops/files/hidden-yaml.json, tests/integration/targets/lookup_sops/files/hidden-yaml.yaml, tests/integration/targets/lookup_sops/tasks/main.yml, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.9.txt
More options for the `sops` lookup.
=> Allow to specify input_type and output_type for sops lookup

CONTRIBUTING.md, README.md
Adds a troubleshooting section to the README, right now only containing information on #34.
Resolves #34.
=> Document gpg troubleshooting

README.md, plugins/lookup/sops.py
=> Fix examples

README.md
See @tadeboro's review (https://github.com/ansible-collections/ansible-inclusion/discussions/9#discussioncomment-285802).
=> add section on releasing, versioning and deprecation to README

plugins/lookup/sops.py, plugins/modules/load_vars.py, plugins/modules/sops_encrypt.py
To prepare for inclusion
Doc formatting (also flake8 swears with unused `dummy`)
=> modules: fix doc formatting

plugins/lookup/sops.py
Fixes #61.
I also decreased the indentation level to save some horizontal screen space (not everyone has a wide screen ;) ).
=> Improve lookup docs

README.md, docs/docsite/rst/guide.rst
I added these while adding the docs for #71, but they should be merged separately (before #71).
=> Small improvements to README and extra docs

changelogs/fragments/83-fix-error-handling.yml, plugins/module_utils/sops.py
Fixes #82.
Check also for negative error codes.
=> Fix error handling

CHANGELOG.rst, changelogs/.plugin-cache.yaml, changelogs/changelog.yaml, changelogs/fragments/1.2.0.yml, changelogs/fragments/81-plugin-options.yml, changelogs/fragments/83-fix-error-handling.yml, galaxy.yml
Release version `1.2.0`
Related to #84
=> release 1.2.0

plugins/vars/sops.py
Fix documentation sanity issue reported by https://github.com/ansible/ansible/pull/77268.
sops vars plugin
=> Fix sanity issue

.github/workflows/ansible-test.yml, README.md, tests/sanity/ignore-2.14.txt
stable-2.13 has been branched. Add it to CI.
CI
=> Add stable-2.13 to CI

.github/workflows/ansible-test.yml, .github/workflows/extra-tests.yml
Spread out nightly CI run times a bit.
CI
=> Schedule nightly CI at 5:30

.github/workflows/ansible-test.yml, README.md, tests/integration/targets/setup_sops/vars/main.yml
And document that the collection has been tested with 3.7.3 in the README.
=> Run tests with latest sops 3.7.3 release

.github/workflows/ansible-test.yml
=> CI matrix: ansible-core's devel version supports Ubuntu 22.04

changelogs/fragments/simplified-bsd-license.yml, plugins/module_utils/sops.py, simplified_bsd.txt
It was referenced in one file, but wasn't there.
collection licenses
=> Add simplified_bsd.txt license file

plugins/modules/sops_encrypt.py, plugins/plugin_utils/action_module.py
Due to new default container for ansible-test `devel`.
various
=> Fix new linting errors

docs/docsite/rst/guide.rst, plugins/filter/decrypt.py, plugins/modules/load_vars.py
https://github.com/ansible-community/community-topics/issues/116
(does not touch the tests)
various
=> Convert yes/no to true/false

docs/docsite/rst/guide.rst
Fix a typo
Typo on word "change"
N/A
=> fix: typo in 'change' word

.github/workflows/extra-tests.yml, .github/workflows/import-galaxy.yml, .github/workflows/reuse.yml
=> Bump GHA checkout version

plugins/doc_fragments/attributes.py, plugins/modules/load_vars.py, plugins/modules/sops_encrypt.py
Uses attributes to document module capabilities.
modules and actions
=> Docment attributes

docs/docsite/rst/guide.rst, plugins/filter/decrypt.py, plugins/lookup/sops.py, plugins/modules/load_vars.py, plugins/modules/sops_encrypt.py, plugins/vars/sops.py
=> Directly reference filters

.github/workflows/ansible-test.yml, changelogs/fragments/132.yml, roles/install/meta/argument_specs.yml, roles/install/tasks/github.yml, tests/integration/targets/role_install_latest/tasks/main.yml, tests/integration/targets/role_install_localhost_remote/tasks/main.yml, tests/integration/targets/role_install_version/tasks/main.yml, tests/integration/targets/setup_sops/tasks/install.yml
Was part of #131, which exposed a bug in ansible-core.
=> install role: use GitHub token if available

.github/workflows/ansible-test.yml, changelogs/fragments/133.yml, plugins/filter/_latest_version.py, roles/install/defaults/main.yml, roles/install/meta/argument_specs.yml, roles/install/tasks/github.yml, roles/install/tasks/github_api.yml, roles/install/tasks/github_latest_release.yml, tests/integration/targets/role_install_latest/tasks/main.yml
See https://github.com/ansible-collections/community.sops/pull/131#issuecomment-1365962115.
=> install role: allow to configure GH latest version detection

changelogs/fragments/remove-unneeded-imports.yml, plugins/action/load_vars.py, plugins/filter/decrypt.py, plugins/module_utils/sops.py, plugins/plugin_utils/action_module.py, plugins/vars/sops.py
Prepare for https://github.com/ansible-collections/news-for-maintainers/issues/34.
various
=> Remove unneccessary imports

tests/ee/roles/lookup_sops/tasks/main.yml, tests/integration/targets/filter_decrypt/tasks/main.yml, tests/integration/targets/load_vars/tasks/main.yml, tests/integration/targets/lookup_sops/tasks/main.yml, tests/integration/targets/setup_remote_tmp_dir/tasks/default-cleanup.yml, tests/integration/targets/sops_encrypt/tasks/main.yml
Continue yes/no → true/false translations.
various
=> Normalize bools in tests

.github/workflows/ee.yml
Try out whether ansible-navigator 3.3.1 fixes the problem; see https://github.com/ansible/ansible-navigator/issues/1448 for context.
=> Use podman instead of docker for EE building

roles/install/meta/argument_specs.yml
Since this is the only role in all community.* collections I maintain, I completely missed it :facepalm:
=> Convert role documentation to semantic markup

.github/workflows/ansible-test.yml
Nightly CI fails: https://github.com/ansible-collections/community.sops/actions/runs/5550853910/jobs/10136369442
=> CI: Replace Fedora 37 with 38 container

.github/workflows/ansible-test.yml, README.md, changelogs/fragments/161-rhel-3.8.0.yml, roles/install/vars/OS-RedHat.yml, tests/integration/targets/role_install_version/tasks/main.yml
Sops 3.8.0 has been released :tada:
=> Test with sops 3.8.0; fix install role for 3.8.0 on RHEL

docs/docsite/rst/guide.rst
Upgrade markup, improve EE examples.
=> Improve docs

CHANGELOG.md, CHANGELOG.rst, changelogs/changelog.yaml, docs/docsite/config.yml
Using the latest antsibull-docs 2.10.0 feature.
docsite
=> Include changelog in docsite

.github/workflows/ansible-test.yml
Ref: https://forum.ansible.com/t/6617
=> Update CI matrix

changelogs/fragments/197-sops-3.9.0-order.yml, plugins/module_utils/sops.py
=> Fix command line argument order for 3.9.0+

changelogs/fragments/208-atomic.yml, plugins/module_utils/io.py
Ref: https://github.com/ansible/ansible/issues/83950
Ref: https://github.com/ansible/ansible/pull/83951/files
io module_utils
=> Pass absolute paths to atmoic_move()

.github/workflows/ansible-test.yml, README.md, plugins/doc_fragments/sops.py, tests/integration/targets/age/tasks/main.yml, tests/integration/targets/age/tasks/test.yml
Ref: https://github.com/getsops/sops/releases/tag/v3.9.1
=> Test SOPS 3.6.1, 3.7.0, and 3.9.1 in CI

.github/workflows/ansible-test.yml, README.md
=> Add SOPS 3.9.2 to CI

.github/workflows/ee.yml, .github/workflows/extra-tests.yml, .github/workflows/reuse.yml
Fix some issues in GHA workflows pointed out by zizmor (https://github.com/woodruffw/zizmor).
CI
=> CI: Fix some issues pointed out by zizmor

plugins/doc_fragments/attributes.py, plugins/doc_fragments/sops.py, plugins/filter/_latest_version.py, plugins/filter/decrypt.py, plugins/lookup/sops.py, plugins/modules/load_vars.py, plugins/modules/sops_encrypt.py, plugins/vars/sops.py
Reformat the YAML documentation embedded into Python files with [andebox](https://pypi.org/project/andebox/).
various
=> Reformat documentation with 'andebox yaml-doc'

changelogs/fragments/221-install-architecture.yml, roles/install/vars/OS-Debian.yml
=> Correctly translate architecture name for Debian

.github/workflows/ansible-test.yml, tests/integration/targets/role_install_latest/tasks/main.yml, tests/integration/targets/role_install_localhost_remote/tasks/main.yml, tests/integration/targets/role_install_version/tasks/main.yml, tests/integration/targets/setup_sops/tasks/install.yml, tests/integration/targets/setup_sops/tasks/main.yml
GHA offers ARM 64 runners: https://github.com/orgs/community/discussions/148648
Let's see if we can do some simple testing on them...
=> Add some ARM 64 tests

noxfile.py, tests/integration/targets/setup_sops/tasks/install.yml
Avoid potential rate limiting. (I'm having problems with this in felixfontein.acme, for example.)
=> CI: Improve SOPS setup

changelogs/fragments/241-support-ssh-keys-for-age.yaml, plugins/doc_fragments/sops.py, plugins/filter/decrypt.py, plugins/module_utils/sops.py
useful feature for my team
support encryption and decryption wtih ssh keys
=> add support ssh keys for age

README.md, antsibull-nox.toml, noxfile.py
=> [stable-1] CI: Replace devel with stable-2.19

tests/integration/targets/sops_encrypt/tasks/main.yml
=> sops_encrypt: adjust test to also work in split-controller situations

changelogs/fragments/255-install-redirects.yml, roles/install/tasks/github_latest_release.yml, tests/integration/targets/age/tasks/test.yml
Found with #254.
Also fixes some bad conditional in an unrelated test.
=> install role: avoid deprecated value of ansible.builtin.uri option

noxfile.py
Debian Trixie (13) was released yesterday: https://www.debian.org/News/2025/20250809
Ref: https://github.com/ansible-community/images/pull/123
CI
=> CI: Add Debian 13 Trixie

changelogs/fragments/262-local-keyservice.yml, plugins/doc_fragments/sops.py, plugins/filter/decrypt.py, plugins/module_utils/sops.py, tests/integration/targets/filter_decrypt/files/fake-sops.sh, tests/integration/targets/filter_decrypt/tasks/main.yml, tests/integration/targets/lookup_sops/files/fake-sops.sh, tests/integration/targets/lookup_sops/tasks/main.yml
=> Fix enable_local_keyservice default to make option actually work when set to False

changelogs/fragments/269-fix.yml, plugins/action/load_vars.py, plugins/plugin_utils/action_module.py
Follow-up to #268. Fix string_types replacement.
various
=> Fix string_types replacement.
